baseURL: "https://lynnstacykegeshi-personalwebsite.netlify.app/"
languageCode: "en-us"
title: "Lynnstacy Kegeshi"
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Lynnstacy"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/lklogonew.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Lynnstacy Kegeshi" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Lynnstacy"
    subtitle: "I integrate actuarial knowledge with data science."
    content: "I am a passionate data scientist who combines actuarial insights with modern analytics. I leverage cutting-edge technologies to transform complex data into meaningful solutions that drive informed decision-making."
    image: /images/lynnprofile.jpeg
    bottomImage:
      enable: true
      roundImage: true 
    button:
      enable: true
      name: "Resume"
      url: "/lynnstacy-kegeshi-cv.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/lynnstacy-kegeshi-b56985235/
        - icon: fab fa-github
          url: https://github.com/lynnstacykegeshi
        - icon: fab fa-x-twitter
          url: https://x.com/lynnstacyk?s=21

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/gradpic.jpeg"
    content: |-
      I am a data scientist based in Kenya. I graduated with first-class honors in Actuarial Science from the University of Nairobi, where my love for data analysis first developed. Combining my actuarial background with a passion for technology, I’ve built expertise in Python, R, machine learning, and AI. I believe that at the intersection of finance and data lies the opportunity for transformation, and I use this perspective to approach every project I work on.

      Currently, I work at Ernst & Young Kenya as a tax advisor, using data analysis to support tax planning. I’m also pursuing actuarial qualifications with the IFoA to deepen my understanding of risk and uncertainty. I'm passionate about problem-solving with data and staying current with AI and machine learning advancements.
    skills:
      enable: true
      title: "Here are some skills I bring to the table:"
      items:
        - "Data Analysis"
        - "R"
        - "Python"
        - "Predictive Modelling"
        - "Data Visualization"
        - "Artificial Intelligence"
        - "Audit"
        - "Tax Advisory"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Tax Advisor"
        company: "Ernst and Young LLP"
        companyUrl: "https://www.ey.com/en_ke"
        date: "Aug 2023 - present"
        featuredLink:
          enable: false
          url: "https://www.ey.com/en_ke"
        info:
          enable: true
          content: Currently working at Ernst & Young LLP Kenya
        content: |
          I am currently working as a tax advisor at [Ernst & Young Kenya](https://www.ey.com/en_ke) in Nairobi Kenya. After gaining foundational experience as an Audit Associate from August 2023 to July 2024, I transitioned in August 2024 to the International Tax and Transfer Pricing sub-service line, where I now support senior team members in delivering tax advisory and compliance services. 
          
          In my current role, my key responsibilities include:
          
          - Tax Due Diligence Support: Assisting with tax due diligence reviews to help clients improve deal structures and minimize tax risks during mergers and acquisitions.
          - Cross-Border Tax Assistance: Supporting tax advisory services related to cross-border transactions, including the tax implications of permanent establishments and foreign operations.
          - Transfer Pricing Documentation: Assisting in the preparation of transfer pricing documentation to comply with local and international regulations, including supporting companies under audit by the Kenya Revenue Authority (KRA) in presenting transfer pricing files.
          - KRA Audit Support: Providing assistance during KRA audits, especially in the preparation and presentation of transfer pricing documents.
          - Tax Compliance: Supporting clients in meeting tax compliance obligations, ensuring accurate and timely submission of tax returns.
          - Research and Analysis: Conducting research on relevant tax laws, treaties, and regulations to help inform tax advisory services.
          - Client Coordination: Working with senior advisors to provide clients with effective tax strategies, ensuring compliance and addressing any cross-border tax issues.
      

      - job: "Attachee"
        company: "REREC"
        companyUrl: "https://www.rerec.co.ke/"
        date: "Jun 2022 - Sept 2022"
        featuredLink:
          enable: false
          url: "https://www.rerec.co.ke/"
        info:
          enable: true
          content: I was an attachee at REREC for 3 months
        content: |
          During my attachment in the Strategy and Planning Department at Rural Electricity and Renewable Energy Corporation (REREC), I developed valuable skills in project data compilation, documentation, and administrative support. 
          
          My daily responsibilities included:

          - Data Management: Supporting the team by entering and organizing various project-related information into the system, ensuring accurate tracking and management of inquiries.
          - Weekly Reporting: Compiling and organizing all entries into a comprehensive weekly report, which I shared with managers for review and approval, facilitating informed decision-making.
          - Document Management: Ensuring that all correspondence and documents were scanned and efficiently forwarded to the relevant departments for further action.
          - File Organization: Maintaining an organized filing system for project documentation to facilitate quick access and retrieval during project implementation.
          - Project Support: Assisting team members in locating files and information as needed to support project planning and execution.


      - job: "Mentor"
        company: "Technovation Girls"
        companyUrl: "https://technovationchallenge.org/"
        date: "Sep 2020 - Dec 2021"
        featuredLink:
          enable: false
          url: "https://technovationchallenge.org/"
        info:
          enable: true
          content: I mentored highschool girls in creating a mobile app.
        content: |
          As a mentor for Technovation Girls, I volunteered to guide a team of five high school girls in developing an innovative app called Fitii using App Inventor. My key responsibilities included:

          - Project Brainstorming: Facilitating brainstorming sessions to help the team identify problems in the health community that the app could address.
          - Technical Guidance: Providing instruction on how to use App Inventor to design and develop the app, ensuring the team understood the technical aspects of the project.
          - Mentorship: Mentoring the girls in project management, helping them define objectives, set milestones, and stay organized throughout the project lifecycle.
          - Problem-Solving: Assisting the team in troubleshooting and resolving challenges encountered during the app development process.
          - Presentation Skills: Coaching the team on how to effectively present their app and ideas, preparing them for pitch events and competitions.


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Science in Data Science"
        school:
          name: "University of Nairobi"
          url: "https://mathematics.uonbi.ac.ke/admission-content-type/master-science-data-science"
        date: "2024 - Ongoing"
        content: |-
          I'm currently pursuing my master's in Data Science, building on my undergraduate degree in Actuarial Science. 
          
          With a strong passion for data-driven insights, I aspire to become a data scientist and explore the intersection of actuarial science and data analytics.
          
          This master's program aligns perfectly with my career goals and my desire to make an impact through data science.
      - title: "Bachelor of Science Actuarial Science"
        school:
          name: "University of Nairobi"
          url: "https://mathematics.uonbi.ac.ke/admission-content-type/master-science-data-science"
        date: "2019 - 2023"
        GPA: "First Class Honours"
        content: |-
          In September 2023, I graduated from the University of Nairobi with first-class honors in Actuarial Science. 
          
          Throughout my four years, I was an active member of NASA, the University of Nairobi Students Actuarial Association. 
          
          One notable achievement during my final year was working on a group project with five other students. Our project focused on investment behavior in money market funds, where we aimed to identify the demographic most likely to invest in such funds in Kenya. Additionally, we used ARIMA models to forecast future investments in money market funds.
          
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Maryhill Girls Highschool Thika"
          url: ""
        GPA: "A- 78 Points, A in Mathematics, A- in English "
        featuredLink:
          enable: false
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: EY Finance Badge 2024
        content: Completed learnings on the EY Finance Badge and successfully applied it to my work
        url: https://www.credly.com/badges/1ca3010a-2992-4029-8717-5b0231b65a51/public_url
        image: /images/ey-finance-bronze.png
      - title: EY Analytics Data Science Badge 2024
        content: Completed Courses on the Data Science and successfully applied it to my work.
        url: https://www.credly.com/badges/c7a80875-5eca-48ff-ad24-5a813ce520d3/public_url
        image: /images/ey-analytics-data-science-bronze.png
      - title: EY Better Me - Wellbeing Badge
        content: Completed learnings to better myself in the workplace
        url: https://www.credly.com/badges/c58a9b14-db76-4e0f-8b05-c025c41e7ef0/public_url
        image: /images/ey-better-me-wellbeing-bronze-learning.png
      - title: EY Artificial Intelligence - Responsible AI
        content: Completed the Responsible AI learnings
        url: https://www.credly.com/badges/25e2b50e-947e-494e-b21a-50c5e2eea4be/public_url
        image: /images/responsibleai.png
      - title: Big Data, Artificial Intelligence and Ethics
        content: Completed the University of California Course on Big Data, UC Davis
        url: https://www.coursera.org/account/accomplishments/verify/LK9GJU74DML6
        image: /images/bigdata-ai-and-ethics.png
      - title: Data Science Ethics
        content: Completed the University of Michigan Course on Data Ethics.
        url: https://www.coursera.org/account/accomplishments/verify/FZEYU7RORS4A
        image: /images/data-science-ethics.PNG
      

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:lynnstacykegeshi@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/lynnstacykegeshi
      linkedin: https://www.linkedin.com/in/lynnstacy-kegeshi-b56985235/
      twitter: https://x.com/lynnstacyk?s=21

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>